// <auto-generated />
namespace DACS_WebNuocHoa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Up_CSDL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Up_CSDL));
        
        string IMigrationMetadata.Id
        {
            get { return "202305161523443_Up_CSDL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
